image: docker:19.03.13-dind

services:
  - docker:19.03.13-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

docker-build:
  stage: package
  script:
   - docker build -t registry.kaseb.xyz/kaseb/kaseb-tracking-report:latest .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.kaseb.xyz
   - docker push registry.kaseb.xyz/kaseb/kaseb-tracking-report
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

docker-tag:
  stage: tag
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.kaseb.xyz
   - docker pull registry.kaseb.xyz/kaseb/kaseb-tracking-report:latest
   - docker tag registry.kaseb.xyz/kaseb/kaseb-tracking-report:latest registry.kaseb.xyz/kaseb/kaseb-tracking-report:$CI_COMMIT_TAG
   - docker push registry.kaseb.xyz/kaseb/kaseb-tracking-report:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

production-deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  variables:
    KUBE_NAMESPACE: production
  environment:
    name: production
    url: https://report.kaseb.xyz/
    kubernetes:
      namespace: production
  script:
    - kubectl -n production set image deployment/tracking-report tracking-report=registry.kaseb.xyz/kaseb/kaseb-tracking-report:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

staging-deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  variables:
    KUBE_NAMESPACE: staging
  environment:
    name: staging
    url: https://devreport.kaseb.xyz/
    kubernetes:
      namespace: staging
  script:
    - kubectl -n staging rollout restart deploy tracking-report
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
