stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/toofun-group/kaseb-tracking-report .
    - docker push registry.gitlab.com/toofun-group/kaseb-tracking-report
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

nl-deploy:
  stage: deploy
  script:
    - whoami
    - sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - sudo docker-compose -f /docker-compose.yml pull tracking-report-server
    - sudo docker-compose -f /docker-compose.yml up -d
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
  tags:
    - nl1